config/routes.rb
Hermes::Application.routes.draw do

  namespace :api, defaults: { format: :json } do
    get 'v1/get',       to: 'v1#get'
    get 'v1/click/:id', to: 'v1#click'
  end

  concern :activated do
    member do
      post 'activate'
      post 'inactivate'
    end
  end

  namespace :admin do
    resources :users
    resources :target_params
  end

  resources :ad_campaigns, concerns: [:activated] do
    resources :ads, concerns: [:activated]
  end

  resources :ad_sizes, only: [:index, :show]


  get  'join',  to: 'session#new',      as: 'join'
  post 'join',  to: 'session#create'
  get  'leave', to: 'session#destroy',  as: 'logout'

  # get  'home',  to: 'dashboard#home',   as: 'dashboard'

  root to: 'redirect#root'
end

app/models/ad_campaign.rb
# == Schema Information
# Schema version: 20150203213425
#
# Table name: ad_campaigns
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  company     :string(255)
#  starting_at :datetime
#  ending_at   :datetime
#  target      :string(255)
#  status      :string(255)
#  deleted_at  :datetime
#  created_at  :datetime
#  updated_at  :datetime
#
# Indexes
#
#  ac_c    (deleted_at,company)
#  ac_s    (deleted_at,status)
#  ac_sse  (deleted_at,status,starting_at,ending_at)
#  ac_x    (deleted_at)
#

class AdCampaign < ActiveRecord::Base
  validates :name,        presence: true
  validates :company,     presence: true
  validates :starting_at, presence: true
  validates :ending_at,   presence: true

  has_many  :ads

  def self.active_ids
    not_deleted.pluck(:id)
  end

  # def count_clicks
  #   Stat.campaign :click, self
  # end
  #
  # def count_requests
  #   Stat.campaign :impression, self
  # end

  def count_active_ads
    ads.with_status(:active).count
  end

  def count_inactive_ads
    ads.with_status(:inactive).count
  end
end

app/controllers/ad_campaigns_controller.rb
class AdCampaignsController < BaseController
  before_action :set_ad_campaign, only: [:show, :edit, :update, :destroy, :activate, :inactivate]

  expose :ad_campaign,     attributes: :ad_campaign_params
  params_for :ad_campaign, :name, :company, :starting_at, :ending_at

  def activate
    @ad_campaign.status = :active
    @ad_campaign.save!
    redirect_to ad_campaigns_path, notice: t('messages.ad_campaigns.activated', name: @ad_campaign.name, company: @ad_campaign.company)
  end

  def inactivate
    @ad_campaign.status = :inactive
    @ad_campaign.save!
    redirect_to ad_campaigns_path, notice: t('messages.ad_campaigns.inactivated', name: @ad_campaign.name, company: @ad_campaign.company)
  end

  def index
    @ad_campaigns = AdCampaign.not_deleted.includes(:ads)
  end

  def show
  end

  def edit
  end

  def new
    @ad_campaign = AdCampaign.new
  end

  def create
    @ad_campaign = AdCampaign.new(ad_campaign_params)

    if @ad_campaign.save
      redirect_to ad_campaigns_path(@ad_campaign), notice: t('messages.ad_campaigns.created', name: @ad_campaign.name, company: @ad_campaign.company)
    else
      render :new
    end
  end

  def update
    if @ad_campaign.update(ad_campaign_params)
      redirect_to ad_campaigns_path(@ad_campaign), notice: t('messages.ad_campaigns.updated', name: @ad_campaign.name, company: @ad_campaign.company)
    else
      render :edit
    end
  end

  def destroy
    @ad_campaign.destroy

    redirect_to ad_campaigns_path, notice: t('messages.ad_campaigns.destroyed', name: @ad_campaign.name, company: @ad_campaign.company)
  end

  private

  def set_ad_campaign
    @ad_campaign = AdCampaign.find(params[:id])
  end
end

app/views/ad_campaigns/_form.html.slim
= simple_form_for [@ad_campaign] do |f|
  = render 'shared/error_box', model: @ad_campaign
  .row
    .small-6.columns
      = f.input  :name
    .small-6.columns
      = f.input  :company
  .row
    .small-6.columns
      = f.input  :starting_at
    .small-6.columns
      = f.input  :ending_at
  .row
    .column
      = f.button :submit, t('.submit')

app/views/ad_campaigns/edit.html.slim
= render 'shared/top_nav_for_record'
= render 'form'

app/views/ad_campaigns/index.html.slim
= render 'shared/top_nav_for_record', count: @ad_campaigns.count
table.column
  thead
    tr
      th.r = t '.th.id'
      th.c = t '.th.status'
      th.c = t '.th.name'
      th.c = t '.th.company'
      th.c = t '.th.from_to'
      th.c = t '.th.ads'
      th.r = t '.th.count_requests'
      th.r = t '.th.count_clicks'
      /th.c = t '.th.target'
      th
  tbody
    - @ad_campaigns.each do |ad_campaign|
      tr
        td.r = ad_campaign.id
        td.c
          - if ad_campaign.count_active_ads > 0
            i.fa.fa-play.fa-fw
          - else
            i.fa.fa-pause.fa-fw
          /= render 'shared/status_icon', status: ad_campaign.status
        td.c = ad_campaign.name
        td.c = ad_campaign.company
        td.c
          = ad_campaign.starting_at.to_formatted_s(:db)
          br
          = ad_campaign.ending_at.to_formatted_s(:db)
        td.c
          = link_to ad_campaign_ads_path(ad_campaign), class: "button inline", title: t('shared.actions.details') do
            i.fa.fa-file-image-o.fa-fw
            = ad_campaign.count_active_ads
            - if ad_campaign.count_inactive_ads > 0
              |&nbsp;+
              = ad_campaign.count_inactive_ads
        td.r = ad_campaign.count_requests
        td.r
          = ad_campaign.count_clicks
          |&nbsp;
          = percent(ad_campaign.count_clicks, ad_campaign.count_requests, "(%.2f%%)")
        /td.c = ad_campaign.target.inspect
        td.actions
          ul.button-group
            /- if ad_campaign.status.active?
            /  li = link_to inactivate_ad_campaign_path(ad_campaign), class: "button", method: :post, data: {confirm: t("shared.are_you_sure")}, title: t('shared.actions.inactivate') do
            /    i.fa.fa-pause.fa-fw
            /- else
            /  li = link_to activate_ad_campaign_path(ad_campaign), class: "button", method: :post, data: {confirm: t("shared.are_you_sure")}, title: t('shared.actions.activate') do
            /    i.fa.fa-play.fa-fw
            li = link_to ad_campaign_path(ad_campaign), class: "button", title: t('shared.actions.show') do
              i.fa.fa-eye.fa-fw
            li = link_to edit_ad_campaign_path(ad_campaign), class: "button", title: t('shared.actions.edit') do
              i.fa.fa-edit.fa-fw
            li = link_to ad_campaign_path(ad_campaign), method: :delete, data: {confirm: t("shared.are_you_sure")}, class: "negative button", title: t('shared.actions.destroy') do
              i.fa.fa-trash.fa-fw

app/views/ad_campaigns/new.html.slim
= render 'shared/top_nav_for_record'
= render 'form'

app/views/ad_campaigns/show.html.slim
= render 'shared/top_nav_for_record'
= render 'shared/show_record_details', what: @ad_campaign