config/routes.rb
Hermes::Application.routes.draw do

  namespace :api, defaults: { format: :json } do
    get 'v1/get',       to: 'v1#get'
    get 'v1/click/:id', to: 'v1#click'
  end

  concern :activated do
    member do
      post 'activate'
      post 'inactivate'
    end
  end

  namespace :admin do
    resources :users
    resources :target_params
  end

  resources :ad_campaigns, concerns: [:activated] do
    resources :ads, concerns: [:activated]
  end

  resources :ad_sizes, only: [:index, :show]


  get  'join',  to: 'session#new',      as: 'join'
  post 'join',  to: 'session#create'
  get  'leave', to: 'session#destroy',  as: 'logout'

  # get  'home',  to: 'dashboard#home',   as: 'dashboard'

  root to: 'redirect#root'
end

app/models/user.rb
# == Schema Information
# Schema version: 20150203213425
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  role            :string(255)
#  locale          :string(255)
#  deleted_at      :datetime
#  created_at      :datetime
#  updated_at      :datetime
#
# Indexes
#
#  us_ep  (deleted_at,email,password_digest)
#  us_r   (deleted_at,role)
#  us_x   (deleted_at)
#

class User < ActiveRecord::Base
  has_secure_password

  enumerize :role,   in: [:user, :admin], scope: true, default: :user
  enumerize :locale, in: [:en, :pl], scope: true, default: :en

  validates :email, presence: true, email: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  expose :user,     attributes: :user_params
  params_for :user, :email, :password, :password_confirmation, :locale

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to edit_admin_user_path(@user), notice: t('messages.users.created')
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to edit_admin_user_path(@user), notice: t('messages.users.updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    redirect_to admin_users_path, notice: t('messages.users.destroyed')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, @user] do |f|
  = render 'shared/error_box', model: @user
  .row
    .column
      = f.input  :email
  .row
    .small-6.columns
      = f.input  :password
    .small-6.columns
      = f.input  :password_confirmation
  .row
    .small-6.columns
      = f.input :role
    .small-6.columns
      = f.input :locale
  .row
    .column
      = f.button :submit, t('.submit')

app/views/admin/users/edit.html.slim
= render 'admin/shared/top_nav'
= render 'form'

app/views/admin/users/index.html.slim
= render 'shared/top_nav_for_record', count: @users.count, prefix: 'admin'
table.column
  thead
    tr
      th.c = t '.th.id'
      th.c = t '.th.email'
      th.c = t '.th.role'
      th.c = t '.th.locale'
      th
  tbody
    - @users.each do |user|
      tr
        td.r = user.id
        td.c = user.email
        td.c = user.role.text
        td.c = user.locale.text
        td.actions
          ul.button-group
            li = link_to admin_user_path(user), class: "button", title: t('shared.actions.show') do
              i.fa.fa-eye.fa-fw
            - if (@current_user.role.admin? or user.role.user?) and not user == @current_user
              li = link_to edit_admin_user_path(user), class: "button", title: t('shared.actions.edit') do
                i.fa.fa-edit.fa-fw
              li = link_to admin_user_path(user), method: :delete, data: {confirm: t("shared.are_you_sure")}, class: "negative button", title: t('shared.actions.destroy') do
                i.fa.fa-trash.fa-fw

app/views/admin/users/new.html.slim
= render 'shared/top_nav_for_record', prefix: 'admin'
= render 'form'

app/views/admin/users/show.html.slim
= render 'shared/top_nav_for_record', prefix: 'admin'
= render 'shared/show_record_details', what: @user