config/routes.rb
Hermes::Application.routes.draw do

  namespace :api, defaults: { format: :json } do
    get 'v1/get',       to: 'v1#get'
    get 'v1/click/:id', to: 'v1#click'
  end

  concern :activated do
    member do
      post 'activate'
      post 'inactivate'
    end
  end

  namespace :admin do
    resources :users
    resources :target_params
  end

  resources :ad_campaigns, concerns: [:activated] do
    resources :ads, concerns: [:activated]
  end

  resources :ad_sizes, only: [:index, :show]


  get  'join',  to: 'session#new',      as: 'join'
  post 'join',  to: 'session#create'
  get  'leave', to: 'session#destroy',  as: 'logout'

  # get  'home',  to: 'dashboard#home',   as: 'dashboard'

  root to: 'redirect#root'
end

app/views/layouts/navigation/_footer.html.slim
#footer
  = image_tag 'logo.svg', alt: '', class: 'logo'
  .quiet.small = t 'app.copyright'

app/views/layouts/navigation/_global.html.slim
nav.top-bar [data-topbar]
  ul.title-area
    li.name
      h1 = link_to root_path do
        = image_tag 'logo.svg', alt: 'Hermes', style: 'height:40px; margin-top: 3px;'
        /= t('app.name')
    li.toggle-topbar.menu-icon
      a href="#"
        span
  a.item.home

  section.top-bar-section
    // right seciton
    ul.right
      li = link_to logout_path, class: 'item' do
        i.off.icon
        = t '.logout'
    ul.left
      li = link_to ad_campaigns_path, class: 'item' do
        = t '.ad_campaigns'
      - if @current_user.role.admin?
        li = link_to admin_users_path, class: 'item' do
          = t '.users'
        /li = link_to admin_target_params_path, class: 'item' do
        /  = t '.target_params'
      li = link_to ad_sizes_path, class: 'item' do
        = t '.ad_sizes'